#cloud-config
autoinstall:
  version: 1
  source:
  id: ubuntu-desktop
  identity:
    hostname: ubuntu-desktop
    username: user
    password: "$6$ZE4WV3QRJhPUnsNv$BpkTBYjUOxOiWV5sNPYDSitTwxW.3NHLmhRqptzpa8a4KTxGpkvMaSDbyq4PVri9kdpD1t7ldUBgwB6uveObg."
  keyboard:
    layout: de
  timezone: Europe/Berlin
  storage:
    layout:
      name: lvm
  packages:
    - vim
    - nano
  snaps:
    - name: teams-for-linux
    - name: onenote-desktop
    - name: code
      classic: true